### ISSUE TITLE
Inserir link nos selos

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/storefront-template#11]
Atualmente nos selos existem apenas a opção de link da imagem e tag alt, sugiro inserir url de destino, pois muitos dos selos levam o lojista para outro local, ou é uma pop up de segurança o que justifica a necessidade do uso para aqueles que precisam. Caso alguém não necessite, deixar a opção como vazio.

**Comment by leomp12** [comment]
@vitorrg podemos fechar?

**Comment by leomp12** [comment]
https://github.com/ecomclub/storefront-template/commit/4eee3a8dbadb7cb3dd3f1da98c9b53132a6da9da
